### ISSUE TITLE
How to avoid automatic scrolling to the top of the page when callbacks are fired?

### ISSUE THREAD

**Issue by aamir-s18** [m93a/svelte-plotly.js#7] opened 2022-12-18 12:50 UTC
Hey, thank you for this great project.

I wanted to use it for a project. Unfortunately, I am running into a bug: Whenever a callback is fired, the page scrolls to the top. 

Here is a minimal example: https://epfl-ada.github.io/ada-2022-project-zozoz
The code: https://github.com/epfl-ada/ada-2022-project-zozoz/tree/main/docs

Maybe you can help out here. Thank you.

**Comment by aamir-s18** [comment] 2022-12-18 19:06
I found a (dirty) fix for it. I added [`data-sveltekit-reload`](https://kit.svelte.dev/docs/link-options#data-sveltekit-reload) to the anchors. So for your example here, it would look like this:

```js
<script>
    import Plot from "svelte-plotly.js";

    let wrapper;
    let changed = false;

    const data = [
        {
            x: [1, 2, 3, 4, 5],
            y: [1, 2, 4, 8, 16],
        },
    ];

    function change() {
        console.log("change");
        if (!changed) {
            const anchors = wrapper.querySelectorAll("a.modebar-btn");
            anchors.forEach((anchor) => {
                anchor.setAttribute("data-sveltekit-reload", "");
            });
            changed = true;
        }
    }
</script>

<div bind:this={wrapper} on:mouseenter={change}>
    <Plot
        {data}
        layout={{
            margin: { t: 0 },
        }}
        fillParent="width"
        debounce={250}
    />
</div>

```

**Comment by cshaa** [comment] 2022-12-19 16:58
Hey Aamir!
Thank you for reporting this! I use this project at work in a SPA app, but I haven't properly tested it in a SvelteKit setup yet. Looks like it's about time that I do :)

**Comment by mitjakukovec** [comment] 2024-05-14 20:52
This issue is preventing the project from gaining wider usage. Is there any progress on fixing it?

**Comment by cshaa** [comment] 2024-06-26 09:50
Hey! Are you still experiencing this issue? My team has been using this package to render tens of plots in a SvelteKit app without running into this issue. I'll close this issue for now, but if anyone still has this bug, please provide steps to reproduce it, and I'll gladly reopen the issue.

**Closed as completed by cshaa** 2024-06-26 09:50 UTC
Labels: bug, help wanted
